### ISSUE TITLE
Bug: Seeking to a negative time won't correctly adjust the song's playing position

### ISSUE THREAD

**Issue by 9382** [YAVSRG/Interlude#260]
I don't know the system well enough to determine a fix myself, but I assume it would be some sort of change to Audio.fs in Flux
If you seek to a negative time in the song (E.g. in the preview menu), the song will remain at the current position (but everything else adjusts)
See video below for an example

https://github.com/YAVSRG/Interlude/assets/49820045/93210ad9-ffde-43b2-9df1-dec6a116178b

**Comment by percyqaz** [comment]
Yeah I noticed this the other day actually
Thanks for the report, will look into it 🤓

**Comment by 9382** [comment]
Fixed in [13efb1b](https://github.com/percyqaz/Percyqaz.Flux/commit/13efb1b602e909c67cdf965215461e598d57f608)
